- locales/en/plugin__activemq-artemis-self-provisioning-plugin.json
- src/brokers/broker-details/BrokerDetails.container.tsx
- src/brokers/broker-details/components/Queues/Queue.component.stories.tsx
- src/brokers/broker-details/components/Queues/QueueRow.tsx
- src/brokers/broker-details/components/Queues/Queues.component.tsx
- src/brokers/broker-details/components/Queues/Queues.container.tsx
- src/brokers/broker-details/components/Queues/index.ts
- src/brokers/broker-details/components/index.ts
> add queues tab to details page

- locales/en/plugin__activemq-artemis-self-provisioning-plugin.json
- src/brokers/broker-details/BrokerDetails.container.tsx
- src/brokers/broker-details/components/Clients/Clients.component.stories.tsx
- src/brokers/broker-details/components/Clients/Clients.component.tsx
- src/brokers/broker-details/components/Clients/Clients.container.tsx
- src/brokers/broker-details/components/Clients/ClientsRow.tsx
- src/brokers/broker-details/components/Clients/index.ts
- src/brokers/broker-details/components/index.ts
> Build components to display clients data

- src/brokers/broker-details/BrokerDetails.container.tsx
- src/brokers/broker-details/components/Topics/Topics.component.stories.tsx
- src/brokers/broker-details/components/Topics/Topics.component.tsx
- src/brokers/broker-details/components/Topics/Topics.container.tsx
- src/brokers/broker-details/components/Topics/TopicsRow.tsx
- src/brokers/broker-details/components/Topics/index.ts
- src/brokers/broker-details/components/index.ts
> Build component to display topics data

- locales/en/plugin__activemq-artemis-self-provisioning-plugin.json
- src/brokers/broker-details/BrokerDetails.container.tsx
- src/brokers/broker-details/components/Clients/Clients.component.tsx
- src/brokers/broker-details/components/Queues/Queues.component.tsx
- src/brokers/broker-details/components/Topics/Topics.component.tsx
- src/common/BrokerDetailsBreadcrumb.tsx
> Add breadcrumb and broker name on broker details

- locales/en/plugin__activemq-artemis-self-provisioning-plugin.json
- src/brokers/add-broker/AddBroker.container.tsx
- src/brokers/add-broker/add-broker-utils.ts
- src/brokers/add-broker/components/EditorToggle/EditorToggle.component.tsx
- src/brokers/add-broker/components/EditorToggle/index.ts
- src/brokers/broker-details/BrokerDetails.container.tsx
- src/brokers/synced-editor/index.ts
- src/shared-components/common/BrokerDetailsBreadcrumb.tsx
- src/shared-components/common/index.ts
> Create Radio buttons component for form and yam editor

- locales/en/plugin__activemq-artemis-self-provisioning-plugin.json
- src/brokers/metrics/Metrics.tsx
- src/brokers/metrics/components/CardBrokerCPUUsageMetrics/CardBrokerCPUUsageMetrics.container.tsx
- src/brokers/metrics/components/CardBrokerMemoryUsageMetrics/CardBrokerMemoryUsageMetrics.container.tsx
- src/brokers/metrics/components/ChartCPUUsage/ChartCPUUsage.tsx
- src/brokers/metrics/components/ChartMemoryUsage/ChartMemoryUsage.tsx
- src/brokers/metrics/components/MetricsActions/MetricsActions.tsx
- src/brokers/metrics/components/MetricsActions/index.ts
- src/brokers/metrics/components/MetricsLayout/MetricsLayout.tsx
- src/brokers/metrics/components/index.ts
- src/brokers/metrics/hooks/useFetchCpuUsageMetrics.tsx
- src/brokers/metrics/hooks/useFetchMemoryUsageMetrics.tsx
- src/shared-components/BrokerDetailsBreadcrumb/BrokerDetailsBreadcrumb.tsx
Add polling and span dropdown and integrate with api
> Add polling and span dropdown and integrate with api

- src/brokers/broker-details/BrokerDetails.container.tsx
- src/shared-components/BrokerDetailsBreadcrumb/BrokerDetailsBreadcrumb.tsx
Add kebab options on details page for edit and delete broker
> Add kebab options on details page for edit and delete broker

- locales/en/plugin__activemq-artemis-self-provisioning-plugin.json
- src/brokers/metrics/Metrics.tsx
- src/brokers/metrics/components/MetricsActions/MetricsActions.tsx
- src/brokers/metrics/components/MetricsLayout/MetricsLayout.tsx
- src/brokers/metrics/hooks/useFetchCpuUsageMetrics.tsx
- src/brokers/metrics/hooks/useFetchMemoryUsageMetrics.tsx
- src/brokers/metrics/utils/format.ts
- src/brokers/metrics/utils/types.ts
Add metrics list dropdown 
User can see list of metrics types in dropdown and can see either all the metrics or single metrics based on selection as given screenshot for reference.
> Add metrics list dropdown 

- src/brokers/metrics/components/MetricsActions/MetricsActions.tsx
> Fix skeleton issue on change span value from dropdown

- src/brokers/broker-details/BrokerDetails.container.tsx
- src/brokers/broker-details/components/Clients/Clients.component.tsx
- src/brokers/broker-details/components/Queues/Queues.component.tsx
- src/brokers/broker-details/components/Topics/Topics.component.tsx
- src/brokers/metrics/components/CardBrokerCPUUsageMetrics/CardBrokerCPUUsageMetrics.container.tsx
- src/brokers/metrics/components/CardBrokerCPUUsageMetrics/index.ts
- src/brokers/metrics/components/CardBrokerMemoryUsageMetrics/CardBrokerMemoryUsageMetrics.container.tsx
- src/brokers/metrics/components/CardBrokerMemoryUsageMetrics/index.ts
- src/brokers/metrics/components/ChartCPUUsage/index.ts
- src/brokers/metrics/components/ChartMemoryUsage/index.ts
- src/shared-components/CardQueryBrowser/CardQueryBrowser.tsx
- src/shared-components/QueryBrowser/QueryBrowser.tsx
- src/shared-components/index.ts
> Create generic/shared component for Metrics 

- package.json
- src/brokers/add-broker/AddBroker.component.tsx
- src/brokers/metrics/components/ChartCPUUsage/ChartCPUUsage.tsx
- src/brokers/metrics/components/ChartMemoryUsage/ChartMemoryUsage.tsx
- src/brokers/metrics/utils/data-utils.ts
- src/brokers/metrics/utils/prometheus.ts
- src/shared-components/QueryBrowser/QueryBrowser.tsx
- src/stories/Page.stories.tsx
- src/utils/prometheus.ts
- tsconfig.json
- webpack.config.ts
- yarn.lock
Add typescript rules  and fix existing issues
https://github.com/artemiscloud/activemq-artemis-self-provisioning-plugin/issues/57
> [#57] Add typescript rules  and fix existing issues

- Dockerfile
- http-server.sh
- package.json
Enhance dockerfile to run container image standalone
> Enhance dockerfile to run container image standalone

- src/shared-components/BrokerDetailsBreadcrumb/BrokerDetailsBreadcrumb.test.tsx
- src/shared-components/BrokerDetailsBreadcrumb/BrokerDetailsBreadcrumb.tsx
- Added unit tests for brokerDetailsBreadcrumb component.
> Unit tests for brokerDetailsBreadcrumb component

- src/brokers/broker-details/BrokerDetails.container.tsx
- src/clients/Clients.component.tsx
- src/queues/Queues.component.tsx
- src/topics/Topics.component.tsx
> Fix Table alignment issue

- start-console.sh
Add x86_64 to fix openshift orgin image arch issue for macbook machine
> Add x86_64 to fix openshift origin image arch issue for macbook machine

- Dockerfile
- http-server.sh
- manifest.yaml
- start-console.sh
- webpack.config.ts
Description:
Fixed deploying plugin with ssl enable. now the plugin is loading in the openshift dev-cluster.
> Deploy plugin with ssl enabled

- package.json
- yarn.lock
Fixed warnings receiving during the image build and while installing dependencies.
> Fix warnings during Docker image build and dependency installation

- .github/renovate.json
- .storybook/withLayout.tsx
- package.json
- src/brokers/add-broker/AddBroker.container.tsx
- src/brokers/add-broker/components/AddBrokerForm/FormView.tsx
- src/brokers/broker-details/BrokerDetails.container.tsx
- src/brokers/update-broker/UpdateBroker.container.tsx
- src/brokers/view-brokers/BrokersList.container.tsx
- src/brokers/view-brokers/components/BrokersList/BrokerRow.tsx
- src/brokers/view-brokers/components/BrokersList/BrokersList.stories.tsx
- src/shared-components/BrokerDetailsBreadcrumb/BrokerDetailsBreadcrumb.test.tsx
- src/shared-components/BrokerDetailsBreadcrumb/BrokerDetailsBreadcrumb.tsx
- start-console-tls.sh
- start-console.sh
- yarn.lock
Reverted React Router v6 migration to maintain compatibility with OCP Version 4.14.0
> Reverted React Router v6 migration to maintain compatibility with OCP Version 4.14.0

- src/shared-components/BrokerDetailsBreadcrumb/BrokerDetailsBreadcrumb.tsx
Integrated 'Delete Broker' modal on Broker Details page.
> Integrate delete broker modal on broker details page

- src/brokers/broker-pods/PodsList.container.tsx
Added functionality to filter pods by namespace.
> Fix: Add Filtering for Pods by Namespace

- src/brokers/broker-details/BrokerDetails.container.tsx
- src/brokers/utils/add-broker.test.ts
- src/brokers/utils/add-broker.ts
- src/configuration/acceptors-config.tsx
- src/utils/types.ts
This PR adds a full coverage of unit testing for the reducer.
> Unit testing for the reducer

- console-extensions.json
- src/brokers/broker-details/BrokerDetails.container.tsx
- src/brokers/broker-pods/PodsList.container.tsx
- src/brokers/broker-pods/components/PodRow.tsx
- src/shared-components/BrokerPodsBreadcrumb/BrokerPodsBreadcrumb.test.tsx
- src/shared-components/BrokerPodsBreadcrumb/BrokerPodsBreadcrumb.tsx
- src/shared-components/BrokerPodsBreadcrumb/index.ts
- src/shared-components/index.ts
Added BrokerDetails breadcrumb page and updated BrokerPods breadcrumb page.
> Add BrokerDetails breadcrumb page

- console-extensions.json
- locales/en/plugin__activemq-artemis-self-provisioning-plugin.json
- package.json
- src/addresses/AddressRow.tsx
- src/addresses/address-details/AddressDetails.component.tsx
- src/addresses/address-details/AddressDetails.container.tsx
- src/addresses/address-details/AddressDetailsRow.tsx
- src/addresses/address-details/index.ts
- src/brokers/broker-details/BrokerDetails.container.tsx
- src/brokers/broker-pods/components/PodList.tsx
- src/shared-components/AddressDetailsBreadcrumb/AddressDetailsBreadcrumb.tsx
> [#163] Address Details page

- src/brokers/broker-details/components/Overview/Overview.container.tsx
We left something that was meant for debug purposes. Cleaning it.
> [NOISSUE] leftover debug tag

- src/brokers/utils/add-broker.ts
- src/configuration/acceptors-config.tsx
- src/configuration/broker-models.tsx
Allow a user to override a certificate value for the acceptor if necessary.
> [NOISSUE] allow custom certificate names

- src/brokers/broker-pods/PodsList.container.tsx
There was a small issue with the broker pods list, in some instances it could return a list of brokers instead of a list of pods. By removing the call that was getting the list of brokers, this is fixed. I also added empty states for when there's no pods in the broker for whatever reasons.
> [NOISSUE] broker pods list, only show pods

- .eslintrc.yml
- src/addresses/address-details/AddressDetails.container.tsx
- src/brokers/add-broker/AddBroker.container.tsx
- src/brokers/add-broker/components/AddBrokerForm/BrokerProperties.tsx
- src/brokers/add-broker/components/AddBrokerForm/FormView.tsx
- src/brokers/broker-details/BrokerDetails.container.tsx
- src/brokers/broker-pods/PodsList.container.tsx
- src/brokers/broker-pods/components/PodList.tsx
- src/brokers/update-broker/UpdateBroker.container.tsx
- src/brokers/utils/add-broker.ts
- src/brokers/view-brokers/BrokersList.container.tsx
- src/configuration/acceptors-config.tsx
- src/configuration/broker-models.tsx
- src/utils/api-server.tsx
Removed unnecessary console.log statements to improve code clarity and performance.
> Remove all the console.log in the codebase

- src/brokers/broker-details/components/Overview/Overview.container.tsx
Use a card like what is done for the metrics.
Add a copy button for the command line the user can use to check the connection.
> [NOISSUE] connectivity card styling

- locales/en/plugin__activemq-artemis-self-provisioning-plugin.json
- src/brokers/view-brokers/components/PreConfirmDeleteModal/PreConfirmDeleteModal.tsx
- src/configuration/acceptors-annotations.tsx
- src/configuration/broker-models.tsx
- src/configuration/cert-manager.tsx
- src/configuration/confirmation-modal.tsx
Refactored Acceptor and Broker delete Modal component.
> [NOISSUE] fix: Refactor Modal component

- README.md
> [NOISSUE] Update Readme

- src/brokers/broker-details/BrokerDetails.container.tsx
Make sure the test panels aren't displayed in prod.
Here's a screen capture of a prod build:
Here's a screen capture of a dev build:
> [#168] hide the jolokia test panels in production

- .github/workflows/release.yml
Instead of the dev.latest as it was previously.
> release: push to the `latest` tag

- README.md
Bump the requested OpenShift version to `4.15`
> Bump the requested OpenShift version

- src/brokers/broker-details/components/Configuration/Configuration.component.tsx
> Refactor: Remove Edit Settings Button from configuration page

- src/brokers/broker-pods/PodsList.container.test.tsx
Added unit test to verify filtering of invalid pod conditions.
> Add unit test to verify filtering of invalid pod conditions

- src/brokers/broker-details/components/Addresses/Address.component.test.tsx
- src/brokers/broker-details/components/Addresses/Address.container.test.tsx
- src/brokers/broker-details/components/Addresses/AddressRow.test.tsx
- Added unit tests for AddressRow comp
- Added unit tests for Address component
- Added unit tests for Address Container comp
fixes: [#274](https://github.com/artemiscloud/activemq-artemis-self-provisioning-plugin/issues/274)
> Add unit tests for all the components in the Addresses folder 

- src/brokers/broker-details/BrokerDetails.container.test.tsx
- Added unit tests for broker details container component.
fixes: [#65](https://github.com/artemiscloud/activemq-artemis-self-provisioning-plugin/issues/65)
> Unit tests for broker details

- console-extensions.json
Reverted the integration of the custom broker edition form within OpenShift.
> [NO-ISSUE] Revert the integration of the broker edition form within Openshift

- .github/actions/cache-restore/action.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- .github/workflows/update.yml
updated node version 16 to 20 and all the deprecation warnings in the CI with latest versions.
> Update Deprecation warnings in the CI
