artemiscloud/activemq-artemis-self-provisioning-plugin

.github/workflows/ci.yml, .github/workflows/release.yml
change buildx to buildah
Tested on fork for amd build: https://github.com/AjayJagan/activemq-artemis-self-provisioning-plugin/actions/runs/5545814880/jobs/10125267727
The arm build takes a lot of time as usual(currently triggered a build and waiting): https://github.com/AjayJagan/activemq-artemis-self-provisioning-plugin/actions/runs/5546642908/jobs/10127203403
I guess we can improve the build time in a separate pr.
The push action was successful for my repo: https://quay.io/repository/ajaganat/quay.io/ajaganat/activemq-artemis-self-provisioning-plugin?tab=tags
=> [#60] change buildx to buildah

package.json, yarn.lock
Resolved the compilation warning caused by the absence of the `CommonProps` export in the `victory-core` package, particularly impacting the `ChartCursorFlyout.js` file in the node_modules. To fix this issue, I updated the victory-core package to ensure that the `CommonProps` export is properly included, enabling seamless import and compilation within the `ChartCursorTooltip` component. This resolution promotes smoother development and eliminates potential errors related to missing exports.
=> Fix import error by resolving missing 'CommonProps' export in victory-core package

start-console-tls.sh
In the `start-console-tls.sh` file, the OCP image version is currently set to `4.14.0.` I have updated it to the `latest` tag version.
=> Updated OCP Version from 4.14.0 to latest in start-console-tls.sh file

src/brokers/view-brokers/components/BrokersList/BrokerRow.tsx
on the remote cluster, there is a broker created without `spec` field. it checks the `spec` field as it's not defined in the broker it prompts error with undefined `deployment` and undefined `size ` on the console.
with some adjustments in the code the issue is fixed.
=> Fixed error while running the plugin in the local development env using remote credentials

.eslintrc.yml, src/brokers/broker-details/index.ts, src/metrics/components/ChartPopover/ChartPopover.test.tsx, src/metrics/components/ChartSkeletonLoader/ChartSkeletonLoader.test.tsx, src/metrics/hooks/useFetchCpuUsageMetrics.tsx, src/metrics/hooks/useFetchMemoryUsageMetrics.tsx, src/shared-components/QueryBrowser/QueryBrowser.tsx, src/stories/button.css, src/stories/header.css
This commit adds:
* the react-hooks plugin to the configuration
* the eqeqeq to the configuration
Also two issues regarding the react-hooks were treated:
Normally it is impossible to call a hook in a conditional branch (if,
loops, ...). That is because it would mess with how React stores it's
data. https://react.dev/reference/rules/rules-of-hooks However in this
specific configuration, the number determining how many loops are
going to occur gets defined by the number of pods within the deployment.
This means this number is guaranteed to stay the same while the page is
displayed, as long as there is no support for the hot reloading of the
deployment details.
/!\ I ran the linter with `yarn lint` and some files got modified along the way.
=> [#121] harden the eslint config

console-extensions.json, locales/en/plugin__activemq-artemis-self-provisioning-plugin.json, package.json, src/brokers/broker-details/BrokerDetails.container.tsx, src/brokers/broker-pods/PodsList.container.tsx, src/brokers/broker-pods/components/PodList.tsx, src/brokers/broker-pods/components/PodRow.tsx, src/brokers/broker-pods/index.ts, src/utils/api-server.tsx
Designed brokers pods page to list set of pods created within specific broker. 
Pods List Page:
Broker Details Page:
=> Implement PodsList Page with User-Selectable Broker Pod for Jolokia Endpoint Access

src/utils/api-server.tsx
When a broker with the default yaml is created, it doesn't have a `spec.console` section, and that was leading to a crash of the UX.
To reproduce the issue, create a broker wit the following spec:
```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
name: default
namespace: default
spec:
deploymentPlan:
image: placeholder
requireLogin: false
size: 1
```
Before the patch it should crash and after the patch it should work fine.
=> api-server: fix undefined access

src/configuration/acceptors-config.tsx
Updated the ToolbarItem to wrap the PlusCircleIcon in a Button component to ensure the cursor changes to a pointer on hover, indicating the button is clickable.
=> [#173] fix: Change cursor to pointer on hover for PlusCircleIcon

locales/en/plugin__activemq-artemis-self-provisioning-plugin.json, src/brokers/utils/add-broker.ts, src/configuration/acceptors-annotations.tsx, src/configuration/acceptors-config.tsx, src/configuration/broker-models.tsx, src/configuration/confirmation-modal.tsx, src/configuration/console-config.tsx
We can leverage the patternFly Form component at the root of the
acceptor and connector configuration page. The Form component handles
the layout for us and removes the need of flex organizers. Also it's
easier to have fields aligning properly without having to deal with
sideeffects when a subcomponent tries to get more space than it was
doing before.
depends on: #162
=> Use patternfly components for the broker form

src/shared-components/AddressDetailsBreadcrumb/AddressDetailsBreadcrumb.tsx, src/shared-components/BrokerDetailsBreadcrumb/BrokerDetailsBreadcrumb.tsx, src/shared-components/BrokerPodsBreadcrumb/BrokerPodsBreadcrumb.tsx
Before, clicking on a link in the breadcrumb was taking a lot of time since it was making the web browser entirely reload the application. Now the links are using the history navigation to change page at a correct pace.
=> [NOISSUE] breadcrumb speed fix

src/brokers/broker-details/BrokerDetails.container.tsx, src/brokers/broker-pods/PodsList.container.tsx, src/metrics/components/MetricsLayout/MetricsLayout.tsx
Adjusted layout by removing padding-left from the wrapper div and adding padding to the title for better alignment with breadcrumb. Applied PatternFly design for the Metrics title.
=> [NOISSUE] Improve UI layout for breadcrumbs and titles

src/brokers/add-broker/AddBroker.component.tsx, src/brokers/add-broker/AddBroker.container.tsx, src/brokers/add-broker/components/AddBrokerForm/FormView.tsx, src/brokers/add-broker/components/AddBrokerForm/YamlEditorView.tsx, src/brokers/update-broker/UpdateBroker.container.tsx, src/brokers/utils/add-broker.ts
Before changing the project had no impact on the state of the CR. Now it does and when the user changes the value of the namespace the value gets propagated using the reducer.
fixes #175
=> [#175] make changing project have an effect

src/brokers/add-broker/components/AddBrokerForm/BrokerProperties.tsx, src/brokers/add-broker/components/AddBrokerForm/FormView.tsx, src/configuration/acceptors-config.tsx, src/configuration/broker-models.tsx, src/configuration/console-config.tsx
Use patternfly components to group items together instead of Flex layouts.
Amongst other improvement:
* empty state for when there's no acceptor / connector
* removing of the inactive search field
* new emplacement for the add button
=> [NOISSUE] form header using patternfly components

src/brokers/view-brokers/components/BrokersList/BrokerRow.tsx
Add a quick access modal to the broker status in the brokers list page. Avoid the need to dig in the yaml just to read the status of a deployment.
=> [NOISSUE] quick access to the broker status

src/brokers/utils/add-broker.test.ts, src/brokers/utils/add-broker.ts, src/configuration/acceptors-config.tsx, src/configuration/other-parameters.tsx
Other parameters are a key value pair. The previous method was relying on a textfield for the user to enter these value as a comma separated list of properties. Now there's a ui component for it showing keys and values in separated text fields. The user can add a new entry, edit it at will and then update or delete it.
[Screencast from 2024-06-20 16-32-19.webm](https://github.com/artemiscloud/activemq-artemis-self-provisioning-plugin/assets/86971992/08ec074b-9a9b-40c6-aa79-fa748ef3b46e)
fixes #177
=> [#177] custom ui element for other parameters

.eslintrc.yml, locales/en/plugin__activemq-artemis-self-provisioning-plugin.json, src/addresses/address-details/AddressDetails.container.tsx, src/brokers/broker-details/BrokerDetails.container.tsx, src/configuration/broker-models.tsx
Removed all alert() calls from the codebase and replaced them with other user notification methods. Added a linter rule to forbid the use of alerts.
=> [#164] remove all alert() from the codebase

README.md
Add details on the documentation about setting up an OpenShift cluster and how to deploy the operator on it. These two steps being requirements for running the plugin successfully.
=> [#119] doc: add details on the OpenShift setup

.github/workflows/release.yml, package.json
As discussed in https://github.com/artemiscloud/activemq-artemis-self-provisioning-plugin/discussions/209 Move to a common version pattern with the operator. Updates also the release action.
=> version: remove the `v` in the version name

.github/workflows/release.yml
The script was crashing most probably because of this:
```
Warning:
"quay.io/***/quay.io/***/activemq-artemis-self-provisioning-plugin" does not seem to be a valid registry path. The registry path should not contain more than 2 slashes. Refer to the Inputs section of the readme for naming image and registry.
```
The build from the ci works however, I'm taking the parametrisation from this workflow to apply it to the release workflow.
=> release: pushing to quay was failing

.github/workflows/merge-rules.yml
The rules validates each pull request's commit message so that it should
* begin with an issue number like [#nnn]
* or begin with [NO-ISSUE] if no issues associated with it
=> [#236] Adding merge rules in workflow

src/shared-components/YamlEditorView/YamlEditorView.tsx
Added margins between buttons and the ActionGroup div in the YAML editor to enhance clearer separation between the buttons and the surrounding div, to improve the UI alignment.
=> Improve Button Alignment in the YAML Editor

src/brokers/broker-pods/components/BrokerPodsBreadcrumb/BrokerPodsBreadcrumb.test.tsx
Added more unit tests to cover all edge cases
improved test coverage for BrokerPodsBreadCrumb component
=> Update unit tests for BrokerPodsBreadcrumb component

src/brokers/broker-pods/PodsList.container.test.tsx, src/brokers/broker-pods/PodsList.container.tsx
- fixed bug with incorrect Pod Filtering for Brokers Starts with similar prefixes/names.
- now, filtering works as expected with selected brokername.
=> fix: Incorrect Pod Filtering for Brokers Starts with similar prefixes/names 

src/brokers/broker-pods/components/PodList.test.tsx, src/brokers/broker-pods/components/PodRow.test.tsx
- Added unit tests for PodRow Component
- Added unit tests for PodList Component
=> Add unit tests for broker-pods components

src/brokers/add-broker/AddBroker.container.tsx, src/brokers/update-broker/UpdateBroker.container.tsx, src/k8s/customHooks.ts, src/k8s/models.ts, src/k8s/types.ts, src/reducers/7.12/reducer.test.ts, src/reducers/7.12/reducer.ts, src/shared-components/FormView/FormView.tsx
The ingress domain can be retrieved from the cluster configuration instead of asking the user to fill in the information themselves. This removes a confusing field from the formview.
This resolves one of the feedback points from @brusdev during the plugin presentation.
fixes #269
=> [#269] remove the ingressDomain field

src/addresses/address-details/AddressDetails.component.tsx, src/addresses/address-details/AddressDetails.container.tsx, src/brokers/broker-details/BrokerDetails.container.tsx, src/brokers/broker-details/components/Addresses/Address.container.tsx, src/brokers/broker-details/components/Addresses/AddressRow.tsx, src/brokers/broker-details/components/JolokiaDevComponents.tsx, src/jolokia/components/JolokiaAuthentication.tsx, src/jolokia/context.ts, src/jolokia/customHooks.ts, src/k8s/customHooks.ts
To minimize code duplication, extract the jolokia login to a new component JolokiaAuthentification. This component does the login and creates a context for its children components.
Now a developer can use this pattern to ensure the component someComponent will get in a logged in context.
```typescript
const AuthenticatedComponent: FC = () => {
const brokerName = 'someName';
const namespace = 'someNamespace';
const podOrdinal = 0;
const { brokerCr } = UseGetBrokerCR(brokerName, namespace);
return (
<JolokiaAuthentification brokerCR={brokerCr} podOrdinal={podOrdinal}>
<SomeComponent />
</JolokiaAuthentification>
);
}
```
=> [NO-ISSUE] refactor how we login to jolokia

src/addresses/address-details/AddressDetails.component.test.tsx, src/addresses/address-details/AddressDetails.container.test.tsx, src/addresses/address-details/AddressDetailsRow.test.tsx
Added unit tests for AddressDetailsRow component
=> Add unit tests for all the components in the addresses/address-details  

src/addresses/address-details/AddressDetails.container.test.tsx, src/addresses/address-details/AddressDetails.container.tsx, src/brokers/add-broker/AddBroker.container.tsx, src/brokers/broker-details/BrokerDetails.container.tsx, src/brokers/update-broker/UpdateBroker.container.tsx, src/k8s/customHooks.ts, src/shared-components/FormView/BrokerProperties/ConfigurationPage/AcceptorsConfigPage/AcceptorConfigSection/PresetButton/PresetButton.tsx, src/shared-components/FormView/BrokerProperties/ConfigurationPage/CertSecretSelector/CertSecretSelector.tsx
Update the cert-manager checking logic to use CRDs instead of checking if cert-manager is deployed in a particular namespace. This is giving better results because cert-manager could have been deployed in many different namespaces.
fixes #222 
fixes #217
=> [#217] checking certManager with CRDs

src/brokers/broker-details/components/Overview/Overview.container.tsx, src/jolokia/context.ts, src/jolokia/customHooks.ts, src/reducers/7.12/reducer.test.ts, src/reducers/7.12/reducer.ts
Add support for multiple hosts to be exposed via an ingress when the user selects several replicas. Each pod gets exposed and has its own url to get connected to.
The connectivity helper shows the url of the currently selected pod.
fixes #192
=> [#192] support multiple hosts for the PEM case

src/reducers/7.12/reducer.test.ts, src/reducers/7.12/reducer.ts
When user adds a new acceptor or connector updated port number to unique instead of a static 5555.
and also added unit tests to verify the logic.
fixes #204
=> Upon adding a new acceptor/connector update the port number to unique

src/reducers/7.12/reducer.test.ts, src/reducers/7.12/reducer.ts
- Updated the logic to generate unique port numbers for `acceptors`and `connectors` separately.
- Updated unit test to verify the unique port assignment for both `acceptors` and `connectors` separately.
fixes: [#279](https://github.com/artemiscloud/activemq-artemis-self-provisioning-plugin/issues/279)
=> Generate unique port numbers for acceptors and connectors separately

src/reducers/7.12/reducer.test.ts, src/reducers/7.12/reducer.ts, src/shared-components/FormView/FormView.tsx
Updated the deployment size should be allowed to reach the value 0.
fixes: [#276](https://github.com/artemiscloud/activemq-artemis-self-provisioning-plugin/issues/276)
=> The deployment size should be allowed to reach the value 0

src/brokers/broker-details/components/Overview/Overview.container.tsx
This commit resolves a crash in the `ConnectivityHelper` component caused by calling the reduce() function on an empty array without an initial value. In cases where the `acceptors` array in the CR's spec is empty, the UI previously crashed due to the lack of an initial value in the reduce operation.
The fix ensures that the reduce function uses `false` as the initial value, making the UI compatible with CRs containing empty `acceptors` arrays.
fixes: [#219](https://github.com/artemiscloud/activemq-artemis-self-provisioning-plugin/issues/219)
=> fix: UI should be compatible with CRs that are containing empty arrays

package.json, src/brokers/add-broker/AddBroker.component.test.tsx, src/brokers/add-broker/AddBroker.component.tsx, src/brokers/add-broker/AddBroker.container.tsx, src/brokers/update-broker/UpdateBroker.container.tsx, src/reducers/7.12/import-types.ts, src/reducers/7.12/reducer.test.ts, src/reducers/7.12/reducer.ts, src/shared-components/FormView/FormView.tsx, src/shared-components/YamlEditorView/YamlEditorView.css, src/shared-components/YamlEditorView/YamlEditorView.tsx, yarn.lock
Previously the yaml editor wasn't allowing us to add new lines. This was because at each keystroke the yaml file was formated automatically, removing unecessary lines..
This meant that the user had to use tricks like copy&pasting to get to a state the wanted to have.
To fix that, this commits reverts back to using the resource editor provided by the console. It has several advantages:
* The use can edit the file as they want without bugs
* There's documentation included from the CRDs when hovering properties
The main drawback is that the user needs to click on save to save their changes to the model, then needs to click on apply to apply their config (either creating or updating)
fixes #198
=> [#198] the yaml editor allows to enter new Lines

src/brokers/view-brokers/BrokersList.container.test.tsx, src/brokers/view-brokers/BrokersList.container.tsx, src/k8s/models.ts
fixed the bug where the broker page refreshes automatically upon broker creation using `useK8sWatchResource` hook.
fixes: [#218](https://github.com/artemiscloud/activemq-artemis-self-provisioning-plugin/issues/218)
=> fix: Broker page refreshes automatically upon broker creation

Dockerfile
Otherwise packages won't get pulled properly when attempting a release.
=> [NO-ISSUE] yarn needs a bigger timeout window

src/shared-components/FormView/BrokerProperties/BrokerProperties.tsx
- Updated the style property from 'list-style' to 'listStyle' to resolve unit test warning. 
- React requires inline styles to be written in camelCase rather than kebab-case.
=> [NO-ISSUE] fix: react unit test warning with 'list-style'

README.md, console-extensions.json
Since Brokers are a type of workload, a shortcut to our project has been added within the Workloads section as 'Brokers' which displays a list of brokers.
fixes: [#294](https://github.com/artemiscloud/activemq-artemis-self-provisioning-plugin/issues/294)
=> [#294] Added 'Brokers' entry within the Workloads section

console-extensions.json
- Added integration of our custom broker creation form within OpenShift. It allows users to create brokers from multiple locations, such as through the OpenShift search results or from the Installed Operators section.
- Users can now utilize our custom broker form to create brokers in both instances.
fixes: [#292](https://github.com/artemiscloud/activemq-artemis-self-provisioning-plugin/issues/292)
=> Integration of broker creation form within OpenShift

console-extensions.json
Reordered `Brokers` Entry to Follow StatefulSets in the Workloads Section.
fixes: [#305](https://github.com/artemiscloud/activemq-artemis-self-provisioning-plugin/issues/305)
=> Move Brokers Entry After StatefulSets in the Workloads Section

console-extensions.json
- Added integration of our custom broker-edition form within OpenShift. It allows users to edit brokers from multiple locations, such as through the OpenShift search results or from the Installed Operators section.
- Users can now utilize our custom broker-edition form to edit brokers in both instances.
=> Integration of the custom broker edition form within OpenShift

src/brokers/add-broker/AddBroker.container.tsx, src/brokers/view-brokers/components/BrokersList/BrokersList.tsx
Updated the handleRedirect logic so that the redirection always navigates back to the previous location after successful broker creation or cancellation, across all instances where the custom form is used.
=> Fix redirect path issue for AddBrokerPage in the Openshift console

console-extensions.json, src/brokers/update-broker/UpdateBroker.container.tsx
- Added integration of our custom broker-edition form within OpenShift. It allows users to edit brokers from multiple locations, such as through the OpenShift search results or from the Installed Operators section.
- Users can now utilize our custom broker-edition form to edit brokers in both the instances. and also updated redirect paths to points to the previous location.
fixes: [#293](https://github.com/artemiscloud/activemq-artemis-self-provisioning-plugin/issues/293)
=> Overhaul the integration of the broker edition form within Openshift

.vscode/launch.json, Dockerfile, charts/openshift-console-plugin/Chart.yaml, package.json
Updated version `0.2.0` to `0.3.0`
=> Update version 0.2.0 to 0.3.0

.devcontainer/Dockerfile.plugin, Dockerfile
The previous base image used nodejs-16, which is outdated. Updated the base image to use nodejs-20 to ensure compatibility and support.
=> Update Dockerfile base image to nodejs-20

deploy-plugin.sh, undeploy-plugin.sh
This should make sure we won't accidentally remove user deployed plugins during un/deployment of our plugin.
=> Deployment should add plugin and remove on undeploy
